package com.soccerwordle.soccer.model;

public class ClWinners {
    private String jsonInputString = """
            [
                 {"year": 2024, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2023, "winner": "Manchester City", "country": "England"},
                 {"year": 2022, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2021, "winner": "Chelsea FC", "country": "England"},
                 {"year": 2020, "winner": "Bayern München", "country": "Deutschland"},
                 {"year": 2019, "winner": "Liverpool FC", "country": "England"},
                 {"year": 2018, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2017, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2016, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2015, "winner": "FC Barcelona", "country": "Spanien"},
                 {"year": 2014, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2013, "winner": "Bayern München", "country": "Deutschland"},
                 {"year": 2012, "winner": "Chelsea FC", "country": "England"},
                 {"year": 2011, "winner": "FC Barcelona", "country": "Spanien"},
                 {"year": 2010, "winner": "Inter Mailand", "country": "Italien"},
                 {"year": 2009, "winner": "FC Barcelona", "country": "Spanien"},
                 {"year": 2008, "winner": "Manchester United", "country": "England"},
                 {"year": 2007, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 2006, "winner": "FC Barcelona", "country": "Spanien"},
                 {"year": 2005, "winner": "Liverpool FC", "country": "England"},
                 {"year": 2004, "winner": "FC Porto", "country": "Portugal"},
                 {"year": 2003, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 2002, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 2001, "winner": "Bayern München", "country": "Deutschland"},
                 {"year": 2000, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1999, "winner": "Manchester United", "country": "England"},
                 {"year": 1998, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1997, "winner": "Borussia Dortmund", "country": "Deutschland"},
                 {"year": 1996, "winner": "Juventus Turin", "country": "Italien"},
                 {"year": 1995, "winner": "Ajax Amsterdam", "country": "Niederlande"},
                 {"year": 1994, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 1993, "winner": "Olympique Marseille", "country": "Frankreich"},
                 {"year": 1992, "winner": "FC Barcelona", "country": "Spanien"},
                 {"year": 1991, "winner": "Roter Stern Belgrad", "country": "Jugoslawien"},
                 {"year": 1990, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 1989, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 1988, "winner": "PSV Eindhoven", "country": "Niederlande"},
                 {"year": 1987, "winner": "FC Porto", "country": "Portugal"},
                 {"year": 1986, "winner": "Steaua Bukarest", "country": "Rumänien"},
                 {"year": 1985, "winner": "Juventus Turin", "country": "Italien"},
                 {"year": 1984, "winner": "Liverpool FC", "country": "England"},
                 {"year": 1983, "winner": "Hamburger SV", "country": "Deutschland"},
                 {"year": 1982, "winner": "Aston Villa", "country": "England"},
                 {"year": 1981, "winner": "Liverpool FC", "country": "England"},
                 {"year": 1980, "winner": "Nottingham Forest", "country": "England"},
                 {"year": 1979, "winner": "Nottingham Forest", "country": "England"},
                 {"year": 1978, "winner": "Liverpool FC", "country": "England"},
                 {"year": 1977, "winner": "Liverpool FC", "country": "England"},
                 {"year": 1976, "winner": "Bayern München", "country": "Deutschland"},
                 {"year": 1975, "winner": "Bayern München", "country": "Deutschland"},
                 {"year": 1974, "winner": "Bayern München", "country": "Deutschland"},
                 {"year": 1973, "winner": "Ajax Amsterdam", "country": "Niederlande"},
                 {"year": 1972, "winner": "Ajax Amsterdam", "country": "Niederlande"},
                 {"year": 1971, "winner": "Ajax Amsterdam", "country": "Niederlande"},
                 {"year": 1970, "winner": "Feyenoord Rotterdam", "country": "Niederlande"},
                 {"year": 1969, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 1968, "winner": "Manchester United", "country": "England"},
                 {"year": 1967, "winner": "Celtic Glasgow", "country": "Schottland"},
                 {"year": 1966, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1965, "winner": "Inter Mailand", "country": "Italien"},
                 {"year": 1964, "winner": "Inter Mailand", "country": "Italien"},
                 {"year": 1963, "winner": "AC Mailand", "country": "Italien"},
                 {"year": 1962, "winner": "Benfica Lissabon", "country": "Portugal"},
                 {"year": 1961, "winner": "Benfica Lissabon", "country": "Portugal"},
                 {"year": 1960, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1959, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1958, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1957, "winner": "Real Madrid", "country": "Spanien"},
                 {"year": 1956, "winner": "Real Madrid", "country": "Spanien"}
             ]
        """;

    public String getJsonInputString() {
        return jsonInputString;
    }
}
